- name: Add openebs repo to helm
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: https://openebs.github.io/openebs
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Install openebs via helm
  kubernetes.core.helm:
    name: openebs
    chart_ref: openebs/openebs
    namespace: openebs
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    skip_schema_validation: true
    update_repo_cache: true
    state: present
