- name: Apply nginx configuration
  ansible.builtin.template:
    src: config.conf.j2
    dest: /etc/nginx/config.conf
    owner: {{ nginx_user }}
    group: {{ nginx_group }}
    mode: '0644'
  notify: restart_nginx
