- name: Create nginx group
  ansible.builtin.group:
    name: "{{ nginx_group }}"
    state: present
  become: true

- name: Create nginx user
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: present
  become: true
