- name: Create nginx user and group
  ansible.builtin.include_tasks: create_nginx_user_group.yml

- name: Install nginx
  ansible.builtin.include_tasks: install_nginx.yml

- name: Apply nginx configuration
  ansible.builtin.include_tasks: apply_configuration.yml
