nginx_user: "nginx"
nginx_worker_processes: 1
nginx_worker_connections: 1024
nginx_external_port: 443
nginx_internal_port: 80
nginx_local_network_server_name: "localhost"
nginx_local_network_cidr: "192.168.1.0/24"
nginx_upstream_service: "localhost"
nginx_upstream_port: 80
nginx_upstream_proto: "http"
nginx_domain: "example.com"
