- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: Install kubernetes python library
  ansible.builtin.pip:
    name: "kubernetes=={{ k8s_python_version }}"
    state: present
  become: true
