- name: Add ingress-nginx repo to helm
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Install ingress-nginx via helm
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    release_values:
      controller:
        service:
          type: "{{ ingress_nginx_service_type }}"
          nodePorts:
            http: "{{ ingress_nginx_service_http_node_port }}"
            https: "{{ ingress_nginx_service_https_node_port }}"
    update_repo_cache: true
    state: present
