---
- hosts: k8s_worker
  roles:
    - {role: zfs/zpool_member, tags: ['zfs']}
  become: true
  become_user: root

- hosts: k8s_controller
  roles:
    - {role: helm_charts/kubernetes_dashboard, tags: ['kubernetes_dashboard']}
    - {role: helm_charts/openebs, tags: ['openebs']}
    - {role: helm_charts/ingress_nginx, tags: ['ingress_nginx']}
    - {role: helm_charts/akri, tags: ['akri']}
    - {role: nginx, tags: ['nginx']}
  become: true
  become_user: root
