---
- hosts: k8s_controller
  roles:
    - {role: common, tags: ['common']}
    - {role: k8s/rpi5_prepare, tags: ['k8s_rpi5_prepare']}
    - {role: docker, tags: ['docker']}
    - {role: k8s/base, tags: ['k8s_base']}
    - {role: k8s/controller, tags: ['k8s_controller']}
    - {role: calico_cni, tags: ['calico_cni']}
  become: true
  become_user: root
