---
- hosts: k8s_worker
  roles:
    - {role: common, tags: ['common']}
    - {role: zfs, tags: ['zfs']}
  become: true
  become_user: root

- hosts: k8s_controller
  roles:
    - {role: common, tags: ['common']}
    - {role: k8s/addons/helm, tags: ['helm']}
    - {role: k8s/addons/k8s_dashboard, tags: ['k8s_dashboard']}
    - {role: zfs, tags: ['zfs']}
    - {role: k8s/addons/openebs, tags: ['openebs']}
  become: true
  become_user: root
