- name: Create Cloudflare dns api token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ cloudflare_api_token_secret_name}}"
        namespace: "{{ homeassistant_namespace }}"
      type: Opaque
      stringData:
        api-token: "{{ cloudflare_api_token | b64encode }}"
    kubeconfig: "{{ k8s_kubectl_config_path }}"
